
output: Messing around.o win_conditions.output
	clang++ Messing around.o message.o -o

Messing around.cpp: Messing around.cpp
	clang++ -c main.cpp

win_conditions.cpp: win_conditions.cpp win_conditions.h
	clang++ -c win_conditions.cpp

clean:
	rm *.o output